### PR TITLE
feat: adds mssql template

### PR DESCRIPTION
**Pull request by EnriqueCoronadoTKSG**
- Adds MSSQL to generate the template for it

### CODE REVIEW

**Review by juan-alonzo — COMMENTED** [review]
Can we validate the dbtype in templates to use root for mysql & postgres and sa for mssql in DB_USER like default values?

**Comment by EnriqueCoronadoTKSG** [comment]
> Can we validate the dbtype in templates to use root for mysql & postgres and sa for mssql in DB_USER like default values?

Actually that is a good idea, and yes it is possible, i will work on this

**Comment by EnriqueCoronadoTKSG** [comment]
Updated with db type check for user of the database

**Review by juan-alonzo — APPROVED** [review]
LGTM

**Pull request merged**
